spring:
  application:
    name: productinventory
  datasource:
    url: jdbc:h2:mem:productinventorydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect