name: Backend Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from build.gradle
        run: |
          VERSION=$(grep -E "version\s*=\s*('[^']+|[^' ]+)" ../../build.gradle | sed -E "s/version\s*=\s*['\"]//;s/['\"]//")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        working-directory: .github/workflows

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mastilovic/productinventory
          tags: ${{ env.VERSION }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
